version: "3.1"
services:

  mongo:
    image: mongo:4.0.4-xenial
    volumes:
      - ${database_dir}:/data/db
    environment:
      - "AUTH=yes"
      - "MONGO_INITDB_ROOT_USERNAME=${db_admin_username}"
      - "MONGO_INITDB_ROOT_PASSWORD=${db_admin_password}"
      - "MONGO_INITDB_DATABASE=${cryptocurrency}"
    ports:
      - 127.0.0.1:${db_port}:27017

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:${mongo_web_admin_port}:8081
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${db_admin_username}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${db_admin_password}"
      - "ME_CONFIG_MONGODB_SERVER=${db_host}"
      - "ME_CONFIG_MONGODB_AUTH_DATABASE=${cryptocurrency}"

  block-engine:
    image: bergplace/block-engine:1.01
    depends_on:
      - mongo
    network_mode: "host"
    environment:
      - "MONGODB_ADMIN_USER=${db_admin_username}"
      - "MONGODB_ADMIN_PASS=${db_admin_password}"
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_PORT=${db_port}"
      - "CRYPTO=${cryptocurrency}"
      - "CRYPTO_USER=${cryptocurrency_rpc_username}"
      - "CRYPTO_PASS=${cryptocurrency_rpc_password}"
      - "CRYPTO_PORT=${cryptocurrency_rpc_port}"
      - "TX_ADDRESS_CACHE_LIMIT=${tx_address_cache_limit}"

  postgres:
    image: postgres:11

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - 127.0.0.1:8002:15672

  celery:
    build:
      context: web/
    volumes:
      - ${task_result_dir}:/task-results
      - ./web/src:/app
    depends_on:
      - postgres
      - rabbit
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_HOST=${db_host}"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=True"
      - "BASE_URL=http://localhost:8000"
      - "TYPE=celery"
      - "CELERY_RDB_HOST='0.0.0.0'"

  web:
    build:
      context: web/
    volumes:
      - ${task_result_dir}:/task-results
      - ./web/src:/app
    depends_on:
      - postgres
      - rabbit
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_HOST=${db_host}"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=True"
      - "BASE_URL=http://localhost:8000"
      - "TYPE=django"
      - "SENDGRID_USERNAME=${sendgrid_username}"
      - "SENDGRID_PASSWORD=${sendgrid_password}"
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    stdin_open: true
