version: "3.1"
services:

  mongo:
    image: mongo:4.0.4-xenial
    volumes:
      - ${database_dir}:/data/db
    environment:
      - "AUTH=yes"
      - "MONGO_INITDB_ROOT_USERNAME=${db_admin_username}"
      - "MONGO_INITDB_ROOT_PASSWORD=${db_admin_password}"
      - "MONGO_INITDB_DATABASE=${cryptocurrency}"
    ports:
      - 127.0.0.1:${db_port}:27017

  block-engine:
    image: bergplace/block-engine:1.01
    depends_on:
      - mongo
    network_mode: "host"
    environment:
      - "MONGODB_ADMIN_USER=${db_admin_username}"
      - "MONGODB_ADMIN_PASS=${db_admin_password}"
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_PORT=${db_port}"
      - "CRYPTO=${cryptocurrency}"
      - "CRYPTO_USER=${cryptocurrency_rpc_username}"
      - "CRYPTO_PASS=${cryptocurrency_rpc_password}"
      - "CRYPTO_PORT=${cryptocurrency_rpc_port}"
      - "TX_ADDRESS_CACHE_LIMIT=${tx_address_cache_limit}"

  postgres:
    image: postgres:11

  rabbit:
    image: rabbitmq:3.7-management

  celery:
    build:
      context: web/
    volumes:
      - ${task_result_dir}:/task-results
      - ./web/src:/app
    depends_on:
      - postgres
      - rabbit
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_HOST=${db_host}"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=False"
      - "BASE_URL=${server_location}"
      - "TYPE=celery"

  web:
    build:
      context: web/
    volumes:
      - ${task_result_dir}:/task-results
      - ./web/src:/app
    depends_on:
      - postgres
      - rabbit
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_HOST=${db_host}"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=False"
      - "BASE_URL=${server_location}"
      - "TYPE=django"
      - "SENDGRID_USERNAME=${sendgrid_username}"
      - "SENDGRID_PASSWORD=${sendgrid_password}"
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    stdin_open: true
