version: "3.2"
services:

  zcashd:
    build:
      context: zcashd/
    volumes:
      - type: $zcashd_volume_type
        source: $zcashd_volume_source
        target: /root/.zcash
    environment:
      - "CRYPTO_USER=${cryptocurrency_rpc_username}"
      - "CRYPTO_PASS=${cryptocurrency_rpc_password}"
      - "CRYPTO_PORT=${cryptocurrency_rpc_port}"
      - "TEST_MODE=${docker_zcash_node_test_mode}"

  mongo:
    image: mongo:4.0.4-xenial
    volumes:
      - type: $mongo_volume_type
        source: $mongo_volume_source
        target: /data/db
    environment:
      - "AUTH=yes"
      - "MONGO_INITDB_ROOT_USERNAME=${mongo_admin_username}"
      - "MONGO_INITDB_ROOT_PASSWORD=${mongo_admin_password}"
      - "MONGO_INITDB_DATABASE=${cryptocurrency}"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:8001:8081
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${mongo_admin_username}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${mongo_admin_password}"
      - "ME_CONFIG_MONGODB_SERVER=mongo"
      - "ME_CONFIG_MONGODB_AUTH_DATABASE=${cryptocurrency}"

  block-engine:
    image: bergplace/block-engine:1.02-testing
    depends_on:
      - mongo
    environment:
      - "MONGODB_ADMIN_USER=${mongo_admin_username}"
      - "MONGODB_ADMIN_PASS=${mongo_admin_password}"
      - "MONGODB_READONLY_USER=${mongo_readonly_username}"
      - "MONGODB_READONLY_PASS=${mongo_readonly_password}"
      - "MONGODB_HOST=mongo"
      - "MONGODB_PORT=27017"
      - "CRYPTO=${cryptocurrency}"
      - "CRYPTO_USER=${cryptocurrency_rpc_username}"
      - "CRYPTO_PASS=${cryptocurrency_rpc_password}"
      - "CRYPTO_PORT=${cryptocurrency_rpc_port}"
      - "CRYPTO_HOST=zcashd"
      - "TX_ADDRESS_CACHE_LIMIT=${tx_address_cache_limit}"

  postgres:
    image: postgres:11

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - 127.0.0.1:8002:15672

  celery:
    build:
      context: web/
    volumes:
      - vol-results:/task-results
      - ./web/src:/app
    depends_on:
      - postgres
      - rabbit
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${mongo_readonly_username}"
      - "MONGODB_READONLY_PASS=${mongo_readonly_password}"
      - "MONGODB_HOST=mongo"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=True"
      - "BASE_URL=http://localhost:8000"
      - "TYPE=celery"
      - "SENDGRID_USERNAME=${sendgrid_username}"
      - "SENDGRID_PASSWORD=${sendgrid_password}"

  web:
    build:
      context: web/
    volumes:
      - vol-results:/task-results
      - ./web/src:/app
    depends_on:
      - postgres
      - rabbit
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${mongo_readonly_username}"
      - "MONGODB_READONLY_PASS=${mongo_readonly_password}"
      - "MONGODB_HOST=mongo"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=True"
      - "BASE_URL=http://localhost:8000"
      - "TYPE=django"
      - "SENDGRID_USERNAME=${sendgrid_username}"
      - "SENDGRID_PASSWORD=${sendgrid_password}"
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    stdin_open: true

volumes:
  vol-results:
  vol-mongo:
  vol-pg:
  vol-rabbit:
  vol-zcashd: